version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres-authservice
    environment:
      POSTGRES_USER: Informatica6c
      POSTGRES_PASSWORD: Informatica
      POSTGRES_DB: DBPrueba_Auth
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: